### ISSUE TITLE
OpenWRT 공유기에 대한 네트워크 메트릭 수집

### ISSUE THREAD

**Issue by Cotidie** [wa-sin-sang-dam/wasin-infra#1]
# 목표

OpenWRT 공유기로부터 네트워크 메트릭을 수집하고 서버 측에 저장할 방법을 고안합시다. 정형화된 시계열 데이터로 저장하여 추후 Grafana라는 시각화 툴을 통해 한 눈에 확인할 수 있어야 합니다. 

# 할일
- [x] #31
- [x] #33
- [x] #34

# 경과

1. 서브도메인 [prometheus.daily-cotidie.com](http://prometheus.daily-cotidie.com) 정의

![Image](https://github.com/user-attachments/assets/03cadb0b-37e5-4a2e-9c59-8d404c6591a6)

1. 서브도메인에 대해 프로메테우스 서버로 트래픽 라우팅

```yaml
# 위치: /grad-project/docker-compose.yaml
services:
  nginx:
    depends_on:
      - prometheus
      - grafana
    image: nginx:1.25.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    networks:
      - monitoring
...
```

# 비고

이제 [[prometheus.daily-cotidie.com](http://prometheus.daily-cotidie.com/)](http://prometheus.daily-cotidie.com) 으로 접속하면 확인할 수 있습니다 !
