### ISSUE TITLE
서버측 Prometheus 설치 및 배포

### ISSUE THREAD

**Issue by Cotidie** [wa-sin-sang-dam/wasin-infra#33]
# 목표
공유기의 OpenWRT에서 전송하는 네트워크 메트릭을 수집할 Prometheus를 라즈베리파이 서버 상에 배포합니다. 

# 경과

1. Prometheus 실행용 설정 파일 정의

```yaml
# 위치: /grad-project/prometheus/prometheus.yaml
global:
  scrape_interval: 30s # set the scraping interval to 30 seconds.
  evaluation_interval: 15s # the interval for evaluating rules.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:9090"]
```

2. Prometheus 도커 실행 용 Compose 설정 정의

```yaml
# 위치: /grad-project/docker-compose.yaml
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring
volumes:
  prom_data:

networks:
  monitoring:
    driver: bridge
```

3. 프로메테우스 서버로 라우팅하기 위한 nginx 설정 정의

```yaml
# 위치: /grad-project/nginx/nginx.conf
http {

  include mime.types;

  set_real_ip_from        0.0.0.0/0;
  real_ip_recursive       on;
  real_ip_header          X-Forward-For;
  limit_req_zone          $binary_remote_addr zone=mylimit:10m rate=10r/s;

  upstream docker-prometheus {
    server prometheus:9090;
  }

  server {
    listen 80;
    server_name [prometheus.daily-cotidie.com](http://prometheus.daily-cotidie.com/);
    root /proxy;
    limit_req zone=mylimit burst=70 nodelay;

    location / {
       proxy_pass http://docker-prometheus; 
    }
  }
}
```
