### ISSUE TITLE
서브도메인을 라우팅하기 위한 Nginx 설정 정의 (Prometheus, Grafana)

### ISSUE THREAD

**Issue by Cotidie** [wa-sin-sang-dam/wasin-infra#37]
# Prometheus
```yaml
# 위치: /grad-project/docker-compose.yaml
services:
  nginx:
    depends_on:
      - prometheus
      - grafana
    image: nginx:1.25.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    networks:
      - monitoring
...
```

# Grafana
```yaml
http {
	...
	
  upstream docker-grafana {
    server grafana:3000;
  }

  server {
    listen 80;
    server_name grafana.daily-cotidie.com;
    root /proxy;
    limit_req zone=mylimit burst=70 nodelay;

    location / {
       proxy_pass http://docker-grafana; 
    }
  }
}
```
